services:

  facilityservice:
    build:
      context: ./FacilityService/FacilityServiceAPI
    expose:
      - "8080"
    networks:
      - backend


  classservice:
    build:
      context: ./ClassServiceAPI
    expose:
      - "8080"
    environment:
      RabbitMQ__Host: rabbitmq
    networks:
      - backend


  messageservice:
    build:
      context: ./MessageServiceAPI
    expose:
      - "8080"
    environment:
      RabbitMQ__Host: rabbitmq
    networks:
      - backend


  ptservice:
    build:
      context: ./PTService/PTServiceAPI
    expose:
      - "8080"
    networks:
      - backend


  rapportservice:
    build:
      context: ./RapportService/RapportServiceAPI
    expose:
      - "8080"
    networks:
      - backend


  authservice:
    build:
      context: ./AuthService/AuthServiceAPI
    expose:
      - "8080"
    networks:
      - backend


  userservice:
    build:
      context: ./UserService/UserService
    expose:
      - "8080"
    networks:
      - backend


networks:
  backend:
    external: true