services:

  frontend:

    build:
      context: ./FitLife.Frontend

    container_name: frontend

    ports:
      - "8080:8080"

    environment:
      ASPNETCORE_URLS: http://+:8080

    networks:
      - backend


networks:

  backend:
    external: true