services:

  facilityservice:
    build:
      context: ./FacilityService/FacilityServiceAPI

    expose:
      - "8080"

    environment:
      - VAULT_TOKEN=${VAULT_TOKEN}
      - Vault__Address=${Vault__Address}

    networks:
      - backend


  classservice:
    build:
      context: ./ClassServiceAPI

    expose:
      - "8080"

    environment:
      - RabbitMQ__Host=rabbitmq
      - VAULT_TOKEN=${VAULT_TOKEN}
      - Vault__Address=${Vault__Address}

    networks:
      - backend


  messageservice:
    build:
      context: ./MessageServiceAPI

    expose:
      - "8080"

    environment:
      - RabbitMQ__Host=rabbitmq
      - VAULT_TOKEN=${VAULT_TOKEN}
      - Vault__Address=${Vault__Address}

    networks:
      - backend


  ptservice:
    build:
      context: ./PTService/PTServiceAPI

    expose:
      - "8080"

    environment:
      - VAULT_TOKEN=${VAULT_TOKEN}
      - Vault__Address=${Vault__Address}

    networks:
      - backend


  statisticservice:
    build:
      context: ./StatisticService/StatisticServiceAPI

    expose:
      - "8080"

    environment:
      - VAULT_TOKEN=${VAULT_TOKEN}
      - Vault__Address=${Vault__Address}

    networks:
      - backend


  authservice:
    build:
      context: ./AuthService/AuthServiceAPI

    expose:
      - "8080"

    environment:
      - VAULT_TOKEN=${VAULT_TOKEN}
      - Vault__Address=${Vault__Address}

    networks:
      - backend


  userservice:
    build:
      context: ./UserService/UserService

    expose:
      - "8080"

    environment:
      - VAULT_TOKEN=${VAULT_TOKEN}
      - Vault__Address=${Vault__Address}

    networks:
      - backend


  digitalcontentservice:
    build:
      context: ./DigitalContentServiceAPI/DigitalContentService/DigitalContentServiceAPI

    expose:
      - "8080"

    environment:
      - VAULT_TOKEN=${VAULT_TOKEN}
      - Vault__Address=${Vault__Address}

    networks:
      - backend


networks:

  backend:
    external: true