# Kører NGINX som nginx-bruger
user nginx;


# Antal samtidige forbindelser
events {
    worker_connections 1000;
}


http {

    #---------- UPSTREAMS ----------
    #Definerer hvilke containere NGINX skal videresende til

    upstream facility_service {
        server facilityservice:8080;
    }

    upstream class_service {
        server classservice:8080;
    }

    upstream message_service {
        server messageservice:8080;
    }

    upstream pt_service {
        server ptservice:8080;
    }

    upstream statistic_service {
        server statisticservice:8080;
    }

    upstream auth_service {
        server authservice:8080;
    }

    upstream user_service {
        server userservice:8080;
    }


    # ---------- API GATEWAY ----------

    server {

        # Port som gateway eksponerer
        listen 4000;


        # Facility
        location /facility/ {
            proxy_pass http://facility_service/;
        }


        # Class
        location /class/ {
            proxy_pass http://class_service/;
        }


        # Message
        location /message/ {
            proxy_pass http://message_service/;
        }


        # PT
        location /pt/ {
            proxy_pass http://pt_service/;
        }


        # Statistic
        location /statistic/ {
            proxy_pass http://statistic_service/;
        }


        # Auth
        location /auth/ {
            proxy_pass http://auth_service/;
        }


        # User
        location /user/ {
            proxy_pass http://user_service/;
        }
    }
}