name: CI

on:
  push:
    branches:
      - Release

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to ACR
      uses: docker/login-action@v3
      with:
        registry: fitlifedigital.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Verify Docker
      run: docker info


    # Frontend
    - name: Build Frontend
      run: |
        docker build \
        -t fitlifedigital.azurecr.io/frontend:latest \
        ./FitLife.Frontend

    - name: Push Frontend
      run: docker push fitlifedigital.azurecr.io/frontend:latest


    # Gateway
    - name: Build Gateway
      run: |
        docker build \
        -t fitlifedigital.azurecr.io/gateway:latest \
        ./nginxForAzure

    - name: Push Gateway
      run: |
        docker push \
        fitlifedigital.azurecr.io/gateway:latest

    # AuthService
    - name: Build AuthService
      run: |
        docker build \
        -t fitlifedigital.azurecr.io/authservice:latest \
        ./AuthService/AuthServiceAPI

    - name: Push AuthService
      run: docker push fitlifedigital.azurecr.io/authservice:latest


    # UserService
    - name: Build UserService
      run: |
        docker build \
        -t fitlifedigital.azurecr.io/userservice:latest \
        ./UserService/UserService

    - name: Push UserService
      run: docker push fitlifedigital.azurecr.io/userservice:latest


    # ClassService
    - name: Build ClassService
      run: |
        docker build \
        -t fitlifedigital.azurecr.io/classservice:latest \
        ./ClassServiceAPI

    - name: Push ClassService
      run: docker push fitlifedigital.azurecr.io/classservice:latest


    # MessageService
    - name: Build MessageService
      run: |
        docker build \
        -t fitlifedigital.azurecr.io/messageservice:latest \
        ./MessageServiceAPI

    - name: Push MessageService
      run: docker push fitlifedigital.azurecr.io/messageservice:latest


    # PTService
    - name: Build PTService
      run: |
        docker build \
        -t fitlifedigital.azurecr.io/ptservice:latest \
        ./PTService/PTServiceAPI

    - name: Push PTService
      run: docker push fitlifedigital.azurecr.io/ptservice:latest


    # FacilityService
    - name: Build FacilityService
      run: |
        docker build \
        -t fitlifedigital.azurecr.io/facilityservice:latest \
        ./FacilityService/FacilityServiceAPI

    - name: Push FacilityService
      run: docker push fitlifedigital.azurecr.io/facilityservice:latest


    # RapportService
    - name: Build StatisticService
      run: |
        docker build \
        -t fitlifedigital.azurecr.io/rapportservice:latest \
        ./StatisticService/StatisticServiceAPI

    - name: Push RapportService
      run: docker push fitlifedigital.azurecr.io/rapportservice:latest
