name: CI

on:
  push:
    branches:
      - Release

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Login to ACR
      uses: docker/login-action@v3
      with:
        registry: fitlifedigital.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Verify
      run: docker info
      
    - name: Generate version
      run: |
        echo "VERSION=0.1.${{ github.run_number }}" >> $GITHUB_ENV

    - name: Build AuthService
      run: |
        docker build \
        -t fitlifedigital.azurecr.io/authservice:${{ env.VERSION }} \
        ./AuthService/AuthServiceAPI

    - name: Push AuthService
      run: |
        docker push \
        fitlifedigital.azurecr.io/authservice:${{ env.VERSION }}

    - name: Show version
      run: |
        echo "Built version: ${{ env.VERSION }}"
